# Generated by Django 2.2.1 on 2019-05-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20170415_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='tags',
        ),
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=[('', '---------')], related_name='notes', to='notes.Tag'),
        ),
    ]
